const colors = {
  PRIMARY: '#3B22AC',
  SECONDARY: '#2AADAD',
};

export const lightTheme = {
  ...colors,
  PRIMARY_BACKGROUND_COLOR: '#F8FAFC',
  SECONDARY_BACKGROUND_COLOR: '#B8BFCC',
  PRIMARY_TEXT_COLOR: '#131314',
  SECONDARY_TEXT_COLOR: 'rgba(19, 19, 20, 0.6)',
};

export const darkTheme = {
  ...colors,
  PRIMARY_BACKGROUND_COLOR: '#030712',
  SECONDARY_BACKGROUND_COLOR: '#1E293B',
  SECONDARY_TEXT_COLOR: '#6C768A',
  PRIMARY_TEXT_COLOR: '#D1D5DB',
};
